apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

replacements:
  - source:
      kind: ConfigMap
      name: project-env-values
      fieldPath: data.PROJECT_SLUG
    targets:
      - select:
          kind: Deployment
          name: web-app
        fieldPaths:
          - spec.template.spec.containers.0.image
