apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: web-ingress
spec:
  routes:
    - match: Host(`c.test.louishaftmann.de`)
      kind: Rule
      services:
        - name: web-service
          port: 3002