apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: test-c-prod
namePrefix: test-c-prod-

configMapGenerator:
- name: project-env-values
  literals:
    - PROJECT_SLUG=test-c
    - ENV_SLUG=prod
  options:
    disableNameSuffixHash: true

images:
- name: test-c-prod-web
  newName: ghcr.io/louishaftmann/kubernetes-test-app
  newTag: 63cbd2ce93b51eec15d285310cf6ca4b96bb868b

components:
- ../../bases/web
# - ../../bases/infisical

configurations:
- ../../configs/kustomize-config.yaml

patches:
- path: ingress.yaml
