apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - secret.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      labelSelector: use-infisical=true
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          secrets.infisical.com/auto-reload: "true"
      - op: add
        path: /spec/template/spec/containers/0/envFrom
        value:
          - secretRef:
              name: managed-secret

replacements:
  - source:
      kind: ConfigMap
      name: project-env-values
      fieldPath: data.PROJECT_SLUG
    targets:
      - select:
          kind: InfisicalSecret
          name: infisical-secret
        fieldPaths:
          - spec.authentication.kubernetesAuth.secretsScope.projectSlug

  - source:
      kind: ConfigMap
      name: project-env-values
      fieldPath: data.ENV_SLUG
    targets:
      - select:
          kind: InfisicalSecret
          name: infisical-secret
        fieldPaths:
          - spec.authentication.kubernetesAuth.secretsScope.envSlug
          
  - source:
      kind: ConfigMap
      name: project-env-values
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: InfisicalSecret
          name: infisical-secret
        fieldPaths:
          - spec.managedKubeSecretReferences.0.secretNamespace