apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - secret.yaml

replacements:
  - source:
      kind: ConfigMap
      name: project-env-values
      fieldPath: data.PROJECT_SLUG
    targets:
      - select:
          kind: InfisicalSecret
          name: infisical-secret
        fieldPaths:
          - spec.authentication.kubernetesAuth.secretsScope.projectSlug

  - source:
      kind: ConfigMap
      name: project-env-values
      fieldPath: data.ENV_SLUG
    targets:
      - select:
          kind: InfisicalSecret
          name: infisical-secret
        fieldPaths:
          - spec.authentication.kubernetesAuth.secretsScope.envSlug
          
  - source:
      kind: ConfigMap
      name: project-env-values
      fieldPath: metadata.namespace
    targets:
      - select:
          kind: InfisicalSecret
          name: infisical-secret
        fieldPaths:
          - spec.managedKubeSecretReferences.0.secretNamespace