nameReference:
- kind: Service
  fieldSpecs:
  - kind: IngressRoute
    group: traefik.io
    path: spec/routes/services/name
  - kind: InfisicalSecret
    group: secrets.infisical.com
    path: spec/managedKubeSecretReferences/secretName