nameReference:
- kind: Service
  fieldSpecs:
  - kind: IngressRoute
    group: traefik.io
    path: spec/routes/services/name
namePrefix:
- path: spec/managedKubeSecretReferences/secretName
  kind: InfisicalSecret
  group: secrets.infisical.com
- kind: Deployment
  group: apps
  path: spec/template/spec/containers/envFrom/secretRef/name
