apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../bases/web
- ../../bases/infisical

namespace: test-b-prod

namePrefix: test-b-prod-

labels:
- includeSelectors: true
  pairs:
    env: production
    project: test-b

configurations:
- ../../configs/kustomize-config.yaml

patches:
- path: ingress.yaml
- path: deployment.yaml
- path: infisical.yaml

images:
- name: test-b
  newName: ghcr.io/louishaftmann/kubernetes-test-app
  newTag: 06598925d24f435cf014600d53c0e5f928245938
